Fix Collision bug
FunnyGuilds/FunnyGuilds pull request #1375
Opened 2020-12-30 16:57 UTC by Rollczi

2020-12-30 17:01 UTC, CDFN commented
In my opinion determinating whether collisions should be enabled should be in configuration. Other option is getting it from bukkit's config.

2020-12-30 17:14 UTC, dzikoysk requested changes

2020-12-30 17:14 UTC, dzikoysk commented on src/main/java/net/dzikoysk/funnyguilds/element/IndividualPrefix.java
> +    private void registerSoloTeam(User member) {
`member`-> `soloUser`

2020-12-30 17:14 UTC, dzikoysk commented on src/main/java/net/dzikoysk/funnyguilds/element/IndividualPrefix.java
> +        for (User u : guild.getMembers()) {
`u` -> `user`

2020-12-30 17:45 UTC, Rollczi commented
```
[18:44:16 ERROR]: Could not pass event PlayerJoinEvent to SMC-Gildie v4.8.0 Tribute-54d99a3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[server.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[server.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) ~[server.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) ~[server.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[server.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[server.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273) ~[server.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[server.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[server.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[server.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[server.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[server.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: Team name 'dziki_wonsz13_one' is longer than the limit of 16 characters
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[server.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:139) ~[server.jar:git-Paper-1618]
        at net.dzikoysk.funnyguilds.element.IndividualPrefix.registerOneTeam(IndividualPrefix.java:233) ~[?:?]
        at net.dzikoysk.funnyguilds.element.IndividualPrefix.initialize(IndividualPrefix.java:201) ~[?:?]
        at net.dzikoysk.funnyguilds.listener.PlayerJoin.onJoin(PlayerJoin.java:65) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor533.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[server.jar:git-Paper-1618]
        ... 14 more

```

2020-12-30 19:26 UTC, CDFN commented
You have to check whether (nickname of player + suffix) is longer than 16 character. There's no workaround for it. I think you should consider choosing other way for creating team name (some identifier?).
Tip: Player's nickname max length is 16 characters.

2021-01-01 19:09 UTC, dzikoysk approved these changes

2021-01-01 19:10 UTC, merged