When player die, There is option to see attacker weapon custom name
FunnyGuilds/FunnyGuilds pull request #1518
Opened 2021-04-18 10:03 UTC by Hound1997c

New place holder {WEAPON-NAME}
+Default its toggled  On in messages.yml

2021-04-18 10:06 UTC, CDFN approved these changes

2021-04-18 11:24 UTC, PinkLolicorn requested changes

2021-04-18 11:24 UTC, PinkLolicorn commented on src/main/java/net/dzikoysk/funnyguilds/util/commons/bukkit/MaterialUtils.java
> +        else return "";
Braces should not be skipped, add braces or use ?:

2021-04-18 11:24 UTC, PinkLolicorn commented on src/main/java/net/dzikoysk/funnyguilds/util/commons/bukkit/MaterialUtils.java
> +        ItemMeta itemMeta = itemStack.getItemMeta();
This is going to throw NPE, itemstacks are frequently nulls

2021-04-18 11:24 UTC, PinkLolicorn commented on src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
> +                .register("{WEAPON-NAME}", MaterialUtils.getItemCustomName(playerAttacker.getItemInHand()))
Unsafe call with nullable value, see comment about MaterialUtils#getItemCustomName(ItemStack)

2021-04-27 16:53 UTC, dzikoysk approved these changes

2021-04-27 16:54 UTC, merged