Rework gui handling.
FunnyGuilds/FunnyGuilds pull request #1568
Opened 2021-06-02 15:52 UTC by Rollczi

Remove unused methods.
Remove the static HashMap for GuiWindow and related methods.
Saves information in non-static holders.
Remove the GuiWindow instance search by title.
GuiWindow is closely related to the holder and inventory.

2021-06-02 20:57 UTC, dzikoysk approved these changes

2021-06-05 19:42 UTC, northpl93 requested changes

2021-06-05 19:42 UTC, northpl93 commented on src/main/java/net/dzikoysk/funnyguilds/element/gui/FunnyHolder.java
> +    public void setCustomer(Integer slot, Consumer<InventoryClickEvent> consumer) {
Was this method meant to be named `setCustomer`?

2021-06-05 19:42 UTC, northpl93 commented on src/main/java/net/dzikoysk/funnyguilds/element/gui/GuiActionHandler.java
> +import org.bukkit.event.inventory.*;
There isn't any project code style, but I think the majority would agree that we should avoid wildcard imports.

2021-06-06 15:20 UTC, merged