Small cleanup
FunnyGuilds/FunnyGuilds pull request #1620
Opened 2021-09-13 17:28 UTC by P3ridot

2021-09-13 19:38 UTC, insertt approved these changes

2021-09-13 19:52 UTC, Rollczi requested changes

2021-09-13 19:52 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/user/UserManager.java
> +    private static UserManager INSTANCE;
Nie jest to jakaś statyczna stała, więc tutaj raczej z małych liter.

2021-09-13 19:57 UTC, dzikoysk requested changes
- Zostawienie regionów w pierwotnej paczce
- Przywrócenie pozmienianego code style

2021-09-14 09:18 UTC, dzikoysk approved these changes

2021-09-14 09:19 UTC, merged