Dependency injection
FunnyGuilds/FunnyGuilds pull request #1653
Opened 2021-09-27 18:28 UTC by P3ridot

2021-09-27 19:00 UTC, Rollczi commented
Liczę na ciebie Peridot  ❤️

2021-09-27 19:01 UTC, P3ridot commented
> Liczę na ciebie Peridot ❤️

Przyda się, przede mną długa droga

2021-09-28 22:12 UTC, Rollczi commented
siema

2021-09-29 17:54 UTC, P3ridot commented
Gotowe do review @dzikoysk ( ͡° ͜ʖ ͡°)

2021-09-30 18:34 UTC, CDFN commented
Changes where :monkey:

2021-09-30 18:49 UTC, P3ridot commented
Never

2021-09-30 20:55 UTC, dzikoysk requested changes

2021-09-30 20:55 UTC, dzikoysk commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/UserBind.java
> +        return userOption.get();
`orNull()`

2021-09-30 20:55 UTC, dzikoysk commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/DeathsCommand.java
> +        sender.sendMessage(this.messageConfig.adminDeathsChanged.replace("{PLAYER}", user.getName()).replace("{DEATHS}", Integer.toString(deaths)));
Rename all `messageConfig` to `messages` as it was before

2021-09-30 20:55 UTC, dzikoysk commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/GuildsEnabledCommand.java
> +        this.pluginConfig.guildsEnabled = !this.pluginConfig.guildsEnabled;
`pluginConfig` -> `config`

2021-09-30 21:15 UTC, dzikoysk approved these changes

2021-09-30 21:16 UTC, dzikoysk commented
Dobra robota!

2021-09-30 21:17 UTC, merged