Fix events a little
FunnyGuilds/FunnyGuilds pull request #1692
Opened 2021-10-24 22:36 UTC by P3ridot

Changes:
* Add AssistsChangeEvent
* Call RankChangeEvents when admin command is used
* Micro-optimization in calculating assists
* Fix checkstyle ( ͡° ͜ʖ ͡°)

2021-10-31 00:59 UTC, Rollczi commented
siema

2021-11-20 17:48 UTC, dzikoysk commented
Resolve conflicts pls

2021-11-20 22:39 UTC, dzikoysk requested changes
1. Określanie wszystkiego jako `changed` nie ma sensu, niech ta nazwa mowi co zostalo zmienione, np. punkty. 
2. Po co ewenty od śmierci itd mają w ogóle to `changed`, raczej umiera sie tylko raz w ramach eventu

2021-11-21 21:47 UTC, P3ridot commented
> 1. Określanie wszystkiego jako `changed` nie ma sensu, niech ta nazwa mowi co zostalo zmienione, np. punkty.
> 2. Po co ewenty od śmierci itd mają w ogóle to `changed`, raczej umiera sie tylko raz w ramach eventu

1. No w sumie można poprawić
2. Te eventy są callowane też jak sie zmienia ilość komendą więc no

2021-11-21 22:51 UTC, Rollczi commented
https://github.com/FunnyGuilds/FunnyGuilds/issues/1488

2021-11-22 20:15 UTC, dzikoysk approved these changes

2021-11-22 20:16 UTC, merged