Small cleanup
FunnyGuilds/FunnyGuilds pull request #1709
Opened 2021-11-22 00:37 UTC by P3ridot

More Javadocs and stop using deprecated methods a little bit more...

2021-11-22 23:03 UTC, dzikoysk requested changes

2021-11-22 23:03 UTC, dzikoysk commented on plugin/src/main/java/net/dzikoysk/funnyguilds/data/util/DeserializationUtils.java
> +        String guildTag = FunnyGuilds.getInstance().getPluginConfiguration().guildTagKeepCase ? (String) values[2] : (FunnyGuilds.getInstance().getPluginConfiguration().guildTagUppercase ? ((String)
```sth ? a : b```
->
```
sth
  ? a
  : b
```

2021-11-22 23:10 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/data/util/DeserializationUtils.java
> +        String guildTag = FunnyGuilds.getInstance().getPluginConfiguration().guildTagKeepCase ? (String) values[2] : (FunnyGuilds.getInstance().getPluginConfiguration().guildTagUppercase ? ((String)
Można jeszcze wyprowadzić `FunnyGuilds.getInstance()` i `(String) values[2]` do osobnych zmiennych

2021-11-23 23:34 UTC, dzikoysk approved these changes

2021-11-23 23:37 UTC, merged