Cleanup in region system
FunnyGuilds/FunnyGuilds pull request #1733
Opened 2021-12-09 02:30 UTC by P3ridot

2021-12-09 02:39 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerJoin.java
> +            if(guild == null) {
witam

2021-12-09 15:04 UTC, dzikoysk requested changes

2021-12-11 09:48 UTC, P3ridot commented on plugin/src/main/java/net/dzikoysk/funnyguilds/listener/BlockFlow.java
>          }
Tu akurat w ogóle widzę, że w cringe sposób jest to zrobione. Zamiast robić to w taki sposób jest metoda isInRegion, która robi dokładnie to samo co zaprezentowany tutaj kod.

2021-12-11 09:53 UTC, P3ridot commented on plugin/src/main/java/net/dzikoysk/funnyguilds/guild/Guild.java
> +                .map(player -> plugin.getRegionManager().findRegionAtLocation(player.getLocation()).getOrNull())
Czemu flatMap?

2021-12-11 11:41 UTC, dzikoysk commented on plugin/src/main/java/net/dzikoysk/funnyguilds/guild/Guild.java
> +                .map(player -> plugin.getRegionManager().findRegionAtLocation(player.getLocation()).getOrNull())
Bo wtedy nie musisz używać `getOrNull`, żeby odpakować Option

2021-12-11 23:15 UTC, Rollczi requested changes

2021-12-11 23:15 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/data/database/SQLDataModel.java
> +                    FunnyGuilds.getInstance().getRegionManager().addRegion(region);
też w methodzie save() przydało by się

2021-12-11 23:15 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/GuildHeartProtectionHandler.java
> +        if (regionOption.isEmpty()) {
można coś takiego:
return FunnyGuilds.getInstance().getRegionManager().findRegionAtLocation(blockLocation)
.map(region -> blockLocation.equals(region.getHeart()))
.orElseGet(false);

ogólnie to ta metoda chyba nie powinna się znajdować tutaj, jest mocno zależna od RegionManager więc można tam ją dać

2021-12-11 23:15 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
> +        this.regionManager = new RegionManager(plugin);
plugin -> this

2021-12-13 22:20 UTC, P3ridot commented on plugin/src/main/java/net/dzikoysk/funnyguilds/data/database/SQLDataModel.java
> +                    FunnyGuilds.getInstance().getRegionManager().addRegion(region);
To się w innym PR naprawi ( ͡° ͜ʖ ͡°)

2021-12-13 22:24 UTC, Rollczi approved these changes

2021-12-13 22:56 UTC, P3ridot commented
Jak coś @dzikoysk to można by w sumie już mergnąć bo @Rollczi potrzebuje

2021-12-13 23:20 UTC, Rollczi approved these changes
Nie podoba mi się dodawanie dokumentacji tak o dla zasady szczególnie, że większość metod jest jasnych w swoich nazwach. Nie było to konieczne, a kod jest teraz dłuższy. Tylko moja opinia.

2021-12-13 23:22 UTC, P3ridot commented
> Nie podoba mi się dodawanie dokumentacji tak o dla zasady szczególnie, że większość metod jest jasnych w swoich nazwach. Nie było to konieczne, a kod jest teraz dłuższy. Tylko moja opinia.

Chce pan zostać pobity? :niezadowolony_pepe:

2021-12-16 13:23 UTC, dzikoysk approved these changes

2021-12-16 13:23 UTC, merged