GH-1818 Unify placeholder system (Resolves #1818)
FunnyGuilds/FunnyGuilds pull request #1883
Opened 2022-03-23 20:55 UTC by P3ridot

#1818

2022-03-23 21:33 UTC, Rollczi requested changes
Co tak faktycznie dają te zmiany tak po za nowymi placeholderami?
Dochodzi 18 plików, ale czy to w ogóle jest konieczne? Kod się wydaje bardziej skomplikowany, mimo że to prosty ficzer. Również bardzo mi tutaj nie odpowiada, że Placeholders są mutable. Robisz też ogrom klas, które wykonują w sumie to samo, tylko zmienia się typ z Gildi np. na Usera (Resolver i Placeholder)

2022-03-23 21:33 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/DeleteAdminCommand.java
> +                .property(Arrays.asList("admin", "player"), new GuildPlaceholder(guildResolver -> sender.getName()))
Trochę mocno jest to przekombinowane

2022-03-23 21:33 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/GuildPlaceholders.java
> +                .property("kdr", new GuildRankPlaceholder((guild, rank) -> String.format(Locale.US, "%.2f", rank.getKDR()), () -> 0.0))
to jeszcze bardziej skomplikowane niż było, i się narobiła nieczytelna masa kodu -> `GuildRankPlaceholder`

2022-03-23 21:33 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/Placeholders.java
> +        this.placeholders.put(name, placeholder);
Usuwasz immutable placeholderów.. przez coś takiego łatwo będzie się robił syf w wypadku jakiegoś błędu  :/

2022-03-24 19:25 UTC, Rollczi requested changes
Proszę przywrócić immutable dla klasy Placeholders

2022-03-24 19:25 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/Placeholders.java
> +    protected Placeholders<T> raw(String name, Placeholder<T> placeholder) {
re: Usuwasz immutable placeholderów.. przez coś takiego łatwo będzie się robił syf w wypadku jakiegoś błędu :/

2022-03-24 19:29 UTC, Rollczi commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/GuildPlaceholders.java
> +                        () -> messages.enemiesNoValue);
Tutaj kiedyś żeby uniknąć tego było:
`BiFunction<Collection<String>, String, Object> joinOrDefault = (list, listNoValue) -> list.isEmpty() ? listNoValue : Joiner.on(", ").join(list);`

2022-03-25 23:32 UTC, Kamilkime requested changes

2022-03-25 23:32 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/placeholderapi/PlaceholderAPIHook.java
> +            Placeholder<User> placeholder = TablistPlaceholders.TABLIST.getPlaceholder("{" + identifier.toUpperCase() + "}");
Można by przenieść doklejanie nawiasów do Placeholders - wtedy wszystkie tego typu rzeczy byłyby tylko w jednym miejscu

2022-03-25 23:32 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/GuildPlaceholders.java
> +                .property("tag", Guild::getTag, () -> messages.gTagNoValue)
Można by to składać jako rozwinięcie kopii tego GUILD

2022-03-25 23:32 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/GuildPlaceholders.java
> +        copy.placeholders.put("{" + name.toUpperCase() + "}", new FallbackPlaceholder<>(resolver, fallbackResolver));
Może to by dać do jakiejś metody statycznej w Placeholders - wtedy dodawanie i usuwanie nawiasów odbywałoby się jedynie w dwóch miejscach

2022-03-25 23:32 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/Placeholders.java
> +                .replace("}", "");
Może lepiej substring bez pierwszego i ostatniego znaku

2022-03-25 23:32 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/UserPlaceholders.java
> +    }
Może lepiej po prostu operować zawsze na Placeholders<T> i nie powielać tyle kodu

2022-04-03 23:27 UTC, dzikoysk commented
Fixnij konflikty

2022-04-10 10:49 UTC, dzikoysk requested changes
Zmień simple placeholders na basic placeholders

2022-04-10 13:04 UTC, merged