GH-1318 Rewrite attacker/victim tracking system (#1318)
FunnyGuilds/FunnyGuilds pull request #2008
Opened 2022-06-20 22:29 UTC by P3ridot

#1318

2022-06-21 09:40 UTC, P3ridot commented on plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
> +        PandaStream.of(assistUsers).forEach(DummyGlobalUpdateUserRequest::new);
Brak delegacji taska, aktualnie tworzymy jedynie jego instancje

2022-06-22 23:17 UTC, dzikoysk requested changes

2022-06-22 23:17 UTC, dzikoysk commented on plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
>  public class PlayerDeath extends AbstractFunnyListener {
Ja bym spróbował podzielić ten listener na jakieś mniejsze funkcje z opisem co robią niż taki jebitny blok kodu.

2022-06-22 23:17 UTC, dzikoysk commented on plugin/src/main/java/net/dzikoysk/funnyguilds/user/DamageCache.java
> +    @Nullable
Czemu nie Option<Damage> itd

2022-06-23 08:19 UTC, P3ridot commented on plugin/src/main/java/net/dzikoysk/funnyguilds/user/DamageCache.java
> +    private final Cache<UUID, Instant> killHistory = CacheBuilder.newBuilder()
Przydałoby sie wymienić ten cache na zwykłą mape. Jeśli pobierzemy z niego wygasniętą wartość to zostanje ona zwrócona ale przy okazji usunieta z cache. Więc dla każdego 2n - 1 (I want to be smort) razu ranking zostanie naliczony.

2022-06-24 10:00 UTC, merged