GH-2111 Add statsreset command
FunnyGuilds/FunnyGuilds pull request #2113
Opened 2022-08-10 20:05 UTC by Astahiell

2022-08-10 20:12 UTC, Kamilkime requested changes

2022-08-10 20:12 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/config/MessageConfiguration.java
> +    public String statsResetMessage ="&7Zresetowales swoje statystyki do podstawowych";
Z tego może lepiej byłoby zrobić listę i pokazać przykładowe użycie dla każdej zmiennej

2022-08-10 20:12 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/FunnyCommandsConfiguration.java
> +import net.dzikoysk.funnyguilds.feature.command.user.*;
Wildcard importów nie używamy

2022-08-10 20:12 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/StatsResetCommand.java
> +        }
Tu może pusta linia

2022-08-10 20:12 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/StatsResetCommand.java
> +        int lastKills = user.getRank().getKills();
Tu może pusta linia

2022-08-23 06:48 UTC, P3ridot requested changes

2022-08-23 06:48 UTC, P3ridot commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/StatsResetCommand.java
> +        user.getRank().setKills(0);
Dodałbym jeszcze resetowanie assyst i logoutów

2022-08-23 06:48 UTC, P3ridot commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/StatsResetCommand.java
> +        int lastRank = user.getRank().getPoints();
Przypisz sobie to user.getRank() do zmiennej np. po prostu `rank` i używaj tej zmiennej

2022-08-23 06:48 UTC, P3ridot commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/StatsResetCommand.java
> +        int lastRank = user.getRank().getPoints();
Zmiwniłbym lastRank -> lastPoints

2022-08-23 06:54 UTC, P3ridot requested changes

2022-08-23 06:54 UTC, P3ridot commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/StatsResetCommand.java
> +                .register("{LAST-DEATH}", lastDeaths)
Chyba powinno byc LAST-DEATH**S** tak samo z placeholderem niżej

2022-08-23 06:54 UTC, P3ridot commented on plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/StatsResetCommand.java
> +                .register("{LAST-RANK}", lastRank)
Tez wymieniłbym RANK -> POINTS

2022-08-23 18:51 UTC, merged