GH-2178 Simpler HEX format (Resolves #2178)
FunnyGuilds/FunnyGuilds pull request #2217
Opened 2022-12-26 23:04 UTC by P3ridot

#2178

2022-12-26 23:12 UTC, Kamilkime requested changes

2022-12-26 23:12 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/ChatUtils.java
> +    private static final Pattern HEX_PATTERN = Pattern.compile("&#([0-9A-Fa-f]{1})([0-9A-Fa-f]{1})([0-9A-Fa-f]{1})([0-9A-Fa-f]{1})([0-9A-Fa-f]{1})([0-9A-Fa-f]{1})");
Może HEX_TO_LEGACY_PATTERN

2022-12-26 23:12 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/ChatUtils.java
> +    private static final Pattern REVERSE_HEX_PATTERN = Pattern.compile("&[xX]&([0-9A-Fa-f]{1})&([0-9A-Fa-f]{1})&([0-9A-Fa-f]{1})&([0-9A-Fa-f]{1})&([0-9A-Fa-f]{1})&([0-9A-Fa-f]{1})");
Może LEGACY_TO_HEX_PATTERN

2022-12-26 23:12 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/ChatUtils.java
> +        message = HEX_PATTERN.matcher(message).replaceAll("&x&$1&$2&$3&$4&$5&$6");
To może do stałej, jakiś LEGACY_COLOR_PATTERN

2022-12-26 23:12 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/ChatUtils.java
> +        rawString = REVERSE_HEX_PATTERN.matcher(rawString).replaceAll("&#$1$2$3$4$5$6");
To może do stałej, jakiś HEX_COLOR_PATTERN

2022-12-26 23:12 UTC, Kamilkime commented on plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/ChatUtils.java
> +        String rawString = DECOLOR_PATTERN.matcher(coloredString).replaceAll("&$1");
To też może przy okazji do jakiejś stałej

2022-12-26 23:37 UTC, DomiRusz24 commented
Akurat chciałem to zrobić, zrobiłem, i widzę że wy już zaczęliście. (I tak zapomniałem decolor zrobić XD) Szacunek za regexy, ja nie mam cierpliwości do nich.

2022-12-26 23:48 UTC, dzikoysk commented
Spoko @DomiRusz24, mamy jeszcze 74 wiszące issues, możesz śmiało brać które chcesz xD

2022-12-27 00:15 UTC, dzikoysk approved these changes

2022-12-27 00:16 UTC, merged