GH-2276 Mitigate player list entry sorting when using ViaVersion
FunnyGuilds/FunnyGuilds pull request #2304
Opened 2023-02-28 17:18 UTC by insertt

In 1.19.3 player list entry sorting got changed and it includes GameProfile name in the sorting process.

To allow players joining with 1.19.3 client on <1.19.3 servers and having proper sorting on the player list, player list now uses proper GameProfile name based on the client's protocol version, retrieved from the ViaVersion's API.

2023-02-28 19:18 UTC, P3ridot requested changes

2023-02-28 19:18 UTC, P3ridot commented on nms/api/src/main/java/net/dzikoysk/funnyguilds/nms/api/ProtocolDependentHelper.java
> +            Class.forName("com.viaversion.viaversion.api.ViaAPI");
Fajnie by było gdybyśmy mogli używać aktualny system do innych hooków niż znowu robić to jakoś oddzielnie

2023-02-28 20:01 UTC, Kamilkime approved these changes

2023-03-02 13:15 UTC, P3ridot approved these changes
Whatever ready to merge zmiany które chcę to w przyszłości zrobimy 😎

2023-03-02 15:39 UTC, merged